### ISSUE TITLE
[ Week 3 ] 3주차 워크북 미션

### ISSUE THREAD

**Issue by jinhyo0** [DS-UMC-7th/UMC-7th-Jinny#7]
### 🛠 Mission

영화 페이지를 만들며, 각각 카테고리에 해당하는 영화 데이터를 불러온다. 

### 📝 To-do

- [x]  `Styled-Components`를 활용하여, 스타일링을 진행하겠습니다. 이전에, className 또는 inline-style로 진행했더라면, 해당 내용을 `Styled-Components`로 수정해주세요!
- [x]  먼저, `root-layout`을 잡아주세요
    - [x]  `navbar`를 최상단에 먼저 배치해주세요.
    - [x]  `sidebar`와 `Outlet`을 가로축으로 배치해주세요.
### navbar 구현

- [x]  로고를 만들어주세요, 로고를 클릭했을 시, `홈페이지로 ‘/’` 이동하여야 합니다.
- [x]  로그인과 회원가입 버튼을 만들어주세요.
    - [x]  버튼이 hover 되었을 시, 색상이 달라지게 UX를 개선해주세요!
    - [x]  로그인 버튼을 클릭시 `‘/login’` 페이지로 이동합니다.
### sidebar 구현

- [x]  **`react-icons`** 라이브러리를 활용하여, 비슷한 아이콘을 활용해주세요!
    
    https://react-icons.github.io/react-icons/
    
- [x]  찾기 버튼 클릭시, `/search` 경로로 이동하며, 아래와 같은 화면을 보이게 해주세요.
- [x] 영화 버튼 클릭시, 아래와 같은 화면이 보이도록 해주세요! 이미지는, 자유롭게 사용하시면 좋습니다!

### 카테고리 페이지
- [x]  현재 상영중인 박스를 클릭하면 `/movies/now-playing 페이지로 이동` 후, 실제 `NowPlaying 영화 데이터`를 불러오기
- [x]  인기있는 박스를 클릭하면 `/movies/popular 페이지로 이동` 후, `실제 Popular 영화 데이터`를 불러오기
- [x]  높은 평가를 받은 박스를 클릭하면 `/movies/top-rated 페이지로 이동` 후, 실제 `TopRated 영화 데이터`를 불러오기
- [x]  개봉 예정중인 박스를 클릭하면 `/movies/up-coming 페이지로 이동` 후, 실제 `UpComing 영화 데이터`를 불러오기
- [x]  각기 다른, 요소의 영화 데이터들이 아래와 같이 불러와진다면 성공입니다.
### 전체적인 체크 사항

- [x]  **`컴포넌트 재사용`**을 했는가?
- [x]  이전에 만들었던 영화 카드 컴포넌트에, 영화 제목과, 개봉일을 추가했는가?
- [x]  **`언어 설정을 한국어`**로 변경했는가?
- [x]  **`Styled-Component`**를 잘 활용했는가?
- [x]  **`폴더 구조`**를 명확히 구분하여, 프로젝트를 진행했는가?

### 🔍 접근 방법

- 리액트의 라우터, 링크 컴포넌트를 통해 메뉴바를 생성한다.
- Styled Components 를 통해 스타일링을 진행한다.
